In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('/content/Instagram_Analytics_Unclean.csv')

print("Original shape:", df.shape)
df.head()

Original shape: (30299, 15)

,post_id,upload_date,media_type,likes,comments,shares,saves,reach,impressions,caption_length,hashtags_count,followers_gained,traffic_source,engagement_rate,content_category
0,IG0018929,2025-08-24 09:25:22.954916,VIDEO,195677.0,2796.0,1083.0,13053.0,868283.0,1045558.0,1376.0,12.0,840.0,home feed,20.33,tech
1,IG0008271,not available,reel,178256.0,7181.0,2344.0,7672.0,1372741.0,1608727.0,1425.0,0.0,957.0,profile,12.15,Fashion
2,IG0011622,2025-01-31 09:25:22.954916,photo,181774.0,8544.0,4395.0,3960.0,595469.0,756588.0,1575.0,9.0,468.0,reels feed,26.26,Lifestyle
3,IG0022342,2025-01-04 09:25:22.954916,photo,7543.0,4043.0,-,1472.0,1837893.0,2255565.0,NaN,20.0,40.0,EXPLORE,0.69,Photography
4,IG0009988,2025-09-17 09:25:22.954916,photo,38122.0,4061.0,4930.0,11498.0,1496253.0,1730399.0,829.0,27.0,757.0,home feed,%error,Photography

In [4]:
print(df.info())

print("\nMissing values:\n", df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30299 entries, 0 to 30298
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   post_id           30299 non-null  object
 1   upload_date       30299 non-null  object
 2   media_type        29693 non-null  object
 3   likes             29420 non-null  object
 4   comments          28820 non-null  float64
 5   shares            29405 non-null  object
 6   saves             29392 non-null  float64
 7   reach             29422 non-null  object
 8   impressions       29402 non-null  float64
 9   caption_length    29387 non-null  float64
 10  hashtags_count    29390 non-null  float64
 11  followers_gained  29385 non-null  float64
 12  traffic_source    29695 non-null  object
 13  engagement_rate   29404 non-null  object
 14  content_category  29696 non-null  object
dtypes: float64(6), object(9)
memory usage: 3.5+ MB
None

Missing values:
 post_id                0
upload_date            0
media_type           606
likes                879
comments            1479
shares               894
saves                907
reach                877
impressions          897
caption_length       912
hashtags_count       909
followers_gained     914
traffic_source       604
engagement_rate      895
content_category     603
dtype: int64

Duplicate rows: 201

In [5]:
df.columns = df.columns.str.strip()
df.columns

Index(['post_id', 'upload_date', 'media_type', 'likes', 'comments', 'shares',
       'saves', 'reach', 'impressions', 'caption_length', 'hashtags_count',
       'followers_gained', 'traffic_source', 'engagement_rate',
       'content_category'],
      dtype='object')

In [6]:
text_cols = ['post_id', 'media_type', 'traffic_source', 'content_category', 'upload_date']

for col in text_cols:
    df[col] = df[col].astype(str).str.strip()

df.head()

,post_id,upload_date,media_type,likes,comments,shares,saves,reach,impressions,caption_length,hashtags_count,followers_gained,traffic_source,engagement_rate,content_category
0,IG0018929,2025-08-24 09:25:22.954916,VIDEO,195677.0,2796.0,1083.0,13053.0,868283.0,1045558.0,1376.0,12.0,840.0,home feed,20.33,tech
1,IG0008271,not available,reel,178256.0,7181.0,2344.0,7672.0,1372741.0,1608727.0,1425.0,0.0,957.0,profile,12.15,Fashion
2,IG0011622,2025-01-31 09:25:22.954916,photo,181774.0,8544.0,4395.0,3960.0,595469.0,756588.0,1575.0,9.0,468.0,reels feed,26.26,Lifestyle
3,IG0022342,2025-01-04 09:25:22.954916,photo,7543.0,4043.0,-,1472.0,1837893.0,2255565.0,NaN,20.0,40.0,EXPLORE,0.69,Photography
4,IG0009988,2025-09-17 09:25:22.954916,photo,38122.0,4061.0,4930.0,11498.0,1496253.0,1730399.0,829.0,27.0,757.0,home feed,%error,Photography

In [7]:
df.replace(['unknown', 'N/A', '-', 'missing', '%error', 'not available', 'nan', 'None'], np.nan, inplace=True)

df.isnull().sum()

post_id                0
upload_date          303
media_type           606
likes               1478
comments            1479
shares              1500
saves                907
reach               1476
impressions          897
caption_length       912
hashtags_count       909
followers_gained     914
traffic_source       604
engagement_rate     1501
content_category     603
dtype: int64

In [8]:
# media_type
df['media_type'] = df['media_type'].replace({
    'photo': 'Photo',
    'VIDEO': 'Video',
    'video': 'Video',
    ' reel ': 'Reel',
    'reel': 'Reel',
    'Carousal': 'Carousel'
})

# traffic_source
df['traffic_source'] = df['traffic_source'].replace({
    'home feed': 'Home Feed',
    'EXPLORE': 'Explore',
    ' profile ': 'Profile',
    'HashTags': 'Hashtags',
    'reels feed': 'Reels Feed',
    'external ': 'External'
})

# content_category
df['content_category'] = df['content_category'].replace({
    'tech': 'Technology',
    ' fitness ': 'Fitness',
    'beauty ': 'Beauty',
    'MUSIC': 'Music',
    ' travel': 'Travel'
})

df.head()

,post_id,upload_date,media_type,likes,comments,shares,saves,reach,impressions,caption_length,hashtags_count,followers_gained,traffic_source,engagement_rate,content_category
0,IG0018929,2025-08-24 09:25:22.954916,Video,195677.0,2796.0,1083.0,13053.0,868283.0,1045558.0,1376.0,12.0,840.0,Home Feed,20.33,Technology
1,IG0008271,NaN,Reel,178256.0,7181.0,2344.0,7672.0,1372741.0,1608727.0,1425.0,0.0,957.0,profile,12.15,Fashion
2,IG0011622,2025-01-31 09:25:22.954916,Photo,181774.0,8544.0,4395.0,3960.0,595469.0,756588.0,1575.0,9.0,468.0,Reels Feed,26.26,Lifestyle
3,IG0022342,2025-01-04 09:25:22.954916,Photo,7543.0,4043.0,NaN,1472.0,1837893.0,2255565.0,NaN,20.0,40.0,Explore,0.69,Photography
4,IG0009988,2025-09-17 09:25:22.954916,Photo,38122.0,4061.0,4930.0,11498.0,1496253.0,1730399.0,829.0,27.0,757.0,Home Feed,NaN,Photography

In [9]:
numeric_cols = [
    'likes', 'comments', 'shares', 'saves', 'reach', 'impressions',
    'caption_length', 'hashtags_count', 'followers_gained', 'engagement_rate'
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.dtypes

post_id              object
upload_date          object
media_type           object
likes               float64
comments            float64
shares              float64
saves               float64
reach               float64
impressions         float64
caption_length      float64
hashtags_count      float64
followers_gained    float64
traffic_source       object
engagement_rate     float64
content_category     object
dtype: object

In [10]:
df['upload_date'] = pd.to_datetime(df['upload_date'], errors='coerce', dayfirst=True)

df.head()

/tmp/ipykernel_12360/4063993563.py:1: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S.%f format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['upload_date'] = pd.to_datetime(df['upload_date'], errors='coerce', dayfirst=True)

,post_id,upload_date,media_type,likes,comments,shares,saves,reach,impressions,caption_length,hashtags_count,followers_gained,traffic_source,engagement_rate,content_category
0,IG0018929,2025-08-24 09:25:22.954916,Video,195677.0,2796.0,1083.0,13053.0,868283.0,1045558.0,1376.0,12.0,840.0,Home Feed,20.33,Technology
1,IG0008271,NaT,Reel,178256.0,7181.0,2344.0,7672.0,1372741.0,1608727.0,1425.0,0.0,957.0,profile,12.15,Fashion
2,IG0011622,2025-01-31 09:25:22.954916,Photo,181774.0,8544.0,4395.0,3960.0,595469.0,756588.0,1575.0,9.0,468.0,Reels Feed,26.26,Lifestyle
3,IG0022342,2025-01-04 09:25:22.954916,Photo,7543.0,4043.0,NaN,1472.0,1837893.0,2255565.0,NaN,20.0,40.0,Explore,0.69,Photography
4,IG0009988,2025-09-17 09:25:22.954916,Photo,38122.0,4061.0,4930.0,11498.0,1496253.0,1730399.0,829.0,27.0,757.0,Home Feed,NaN,Photography

In [11]:
print("Duplicates before:", df.duplicated().sum())

df = df.drop_duplicates()

print("After removal:", df.duplicated().sum())
print("New shape:", df.shape)

Duplicates before: 212
After removal: 0
New shape: (30087, 15)

In [12]:
for col in numeric_cols:
    df.loc[df[col] < 0, col] = np.nan

df.describe()

,upload_date,likes,comments,shares,saves,reach,impressions,caption_length,hashtags_count,followers_gained,engagement_rate
count,28594,28614.000000,28311.000000,28592.000000,29183.000000,2.861700e+04,2.889100e+04,29181.000000,29184.000000,29182.000000,28591.000000
mean,2025-05-19 22:00:13.911060736,109277.646117,5020.870015,2507.060192,7490.138985,1.092533e+06,1.247698e+06,1102.983105,14.874657,502.728394,14.422199
min,2024-11-19 09:25:22.954916,7.000000,0.000000,0.000000,0.000000,1.650000e+02,5.107000e+03,0.000000,0.000000,0.000000,0.120000
25%,2025-02-18 09:25:22.954916096,50123.250000,2529.500000,1253.000000,3691.000000,4.980220e+05,7.486895e+05,553.000000,7.000000,251.000000,5.170000
50%,2025-05-19 09:25:22.954916096,100523.000000,5048.000000,2508.500000,7480.000000,1.004276e+06,1.242477e+06,1100.000000,15.000000,502.000000,9.200000
75%,2025-08-19 09:25:22.954916096,151628.750000,7518.500000,3770.000000,11300.500000,1.512935e+06,1.750277e+06,1656.000000,23.000000,756.000000,15.670000
max,2025-11-19 09:25:22.954916,999999.000000,10000.000000,5000.000000,15000.000000,9.999999e+06,2.497940e+06,2200.000000,30.000000,1000.000000,3259.820000
std,NaN,108524.592544,2888.495003,1446.699123,4354.030992,1.086055e+06,5.970379e+05,636.190479,9.003994,290.381034,29.994224

In [13]:
def treat_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    data.loc[(data[column] < lower) | (data[column] > upper), column] = np.nan
    return data

for col in numeric_cols:
    df = treat_outliers_iqr(df, col)

df.describe()

,upload_date,likes,comments,shares,saves,reach,impressions,caption_length,hashtags_count,followers_gained,engagement_rate
count,28594,28312.000000,28311.000000,28592.000000,29183.000000,2.831400e+04,2.889100e+04,29181.000000,29184.000000,29182.000000,26158.000000
mean,2025-05-19 22:00:13.911060736,99776.450551,5020.870015,2507.060192,7490.138985,9.972106e+05,1.247698e+06,1102.983105,14.874657,502.728394,9.948986
min,2024-11-19 09:25:22.954916,7.000000,0.000000,0.000000,0.000000,1.650000e+02,5.107000e+03,0.000000,0.000000,0.000000,0.120000
25%,2025-02-18 09:25:22.954916096,49552.250000,2529.500000,1253.000000,3691.000000,4.929660e+05,7.486895e+05,553.000000,7.000000,251.000000,4.840000
50%,2025-05-19 09:25:22.954916096,99382.000000,5048.000000,2508.500000,7480.000000,9.937210e+05,1.242477e+06,1100.000000,15.000000,502.000000,8.540000
75%,2025-08-19 09:25:22.954916096,149997.000000,7518.500000,3770.000000,11300.500000,1.495530e+06,1.750277e+06,1656.000000,23.000000,756.000000,13.387500
max,2025-11-19 09:25:22.954916,200000.000000,10000.000000,5000.000000,15000.000000,1.999865e+06,2.497940e+06,2200.000000,30.000000,1000.000000,31.420000
std,NaN,57876.841903,2888.495003,1446.699123,4354.030992,5.778755e+05,5.970379e+05,636.190479,9.003994,290.381034,6.737242

In [14]:
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

df.isnull().sum()

post_id                0
upload_date         1493
media_type           602
likes                  0
comments               0
shares                 0
saves                  0
reach                  0
impressions            0
caption_length         0
hashtags_count         0
followers_gained       0
traffic_source       600
engagement_rate        0
content_category     601
dtype: int64

In [15]:
cat_cols = ['media_type', 'traffic_source', 'content_category']

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

df.isnull().sum()

post_id                0
upload_date         1493
media_type             0
likes                  0
comments               0
shares                 0
saves                  0
reach                  0
impressions            0
caption_length         0
hashtags_count         0
followers_gained       0
traffic_source         0
engagement_rate        0
content_category       0
dtype: int64

In [16]:
df['post_id'] = df['post_id'].replace('nan', np.nan)
df['post_id'] = df['post_id'].fillna('Unknown_ID')

df.head()

,post_id,upload_date,media_type,likes,comments,shares,saves,reach,impressions,caption_length,hashtags_count,followers_gained,traffic_source,engagement_rate,content_category
0,IG0018929,2025-08-24 09:25:22.954916,Video,195677.0,2796.0,1083.0,13053.0,868283.0,1045558.0,1376.0,12.0,840.0,Home Feed,20.33,Technology
1,IG0008271,NaT,Reel,178256.0,7181.0,2344.0,7672.0,1372741.0,1608727.0,1425.0,0.0,957.0,profile,12.15,Fashion
2,IG0011622,2025-01-31 09:25:22.954916,Photo,181774.0,8544.0,4395.0,3960.0,595469.0,756588.0,1575.0,9.0,468.0,Reels Feed,26.26,Lifestyle
3,IG0022342,2025-01-04 09:25:22.954916,Photo,7543.0,4043.0,2508.5,1472.0,1837893.0,2255565.0,1100.0,20.0,40.0,Explore,0.69,Photography
4,IG0009988,2025-09-17 09:25:22.954916,Photo,38122.0,4061.0,4930.0,11498.0,1496253.0,1730399.0,829.0,27.0,757.0,Home Feed,8.54,Photography

In [17]:
valid_dates = df['upload_date'].dropna().sort_values()

if len(valid_dates) > 0:
    middle_date = valid_dates.iloc[len(valid_dates)//2]
    df['upload_date'] = df['upload_date'].fillna(middle_date)

df.head()

,post_id,upload_date,media_type,likes,comments,shares,saves,reach,impressions,caption_length,hashtags_count,followers_gained,traffic_source,engagement_rate,content_category
0,IG0018929,2025-08-24 09:25:22.954916,Video,195677.0,2796.0,1083.0,13053.0,868283.0,1045558.0,1376.0,12.0,840.0,Home Feed,20.33,Technology
1,IG0008271,2025-05-19 09:25:22.954916,Reel,178256.0,7181.0,2344.0,7672.0,1372741.0,1608727.0,1425.0,0.0,957.0,profile,12.15,Fashion
2,IG0011622,2025-01-31 09:25:22.954916,Photo,181774.0,8544.0,4395.0,3960.0,595469.0,756588.0,1575.0,9.0,468.0,Reels Feed,26.26,Lifestyle
3,IG0022342,2025-01-04 09:25:22.954916,Photo,7543.0,4043.0,2508.5,1472.0,1837893.0,2255565.0,1100.0,20.0,40.0,Explore,0.69,Photography
4,IG0009988,2025-09-17 09:25:22.954916,Photo,38122.0,4061.0,4930.0,11498.0,1496253.0,1730399.0,829.0,27.0,757.0,Home Feed,8.54,Photography

In [18]:
df['engagement_rate'] = df['engagement_rate'].round(2)

df['upload_date'] = df['upload_date'].dt.strftime('%Y-%m-%d')

df.head()

,post_id,upload_date,media_type,likes,comments,shares,saves,reach,impressions,caption_length,hashtags_count,followers_gained,traffic_source,engagement_rate,content_category
0,IG0018929,2025-08-24,Video,195677.0,2796.0,1083.0,13053.0,868283.0,1045558.0,1376.0,12.0,840.0,Home Feed,20.33,Technology
1,IG0008271,2025-05-19,Reel,178256.0,7181.0,2344.0,7672.0,1372741.0,1608727.0,1425.0,0.0,957.0,profile,12.15,Fashion
2,IG0011622,2025-01-31,Photo,181774.0,8544.0,4395.0,3960.0,595469.0,756588.0,1575.0,9.0,468.0,Reels Feed,26.26,Lifestyle
3,IG0022342,2025-01-04,Photo,7543.0,4043.0,2508.5,1472.0,1837893.0,2255565.0,1100.0,20.0,40.0,Explore,0.69,Photography
4,IG0009988,2025-09-17,Photo,38122.0,4061.0,4930.0,11498.0,1496253.0,1730399.0,829.0,27.0,757.0,Home Feed,8.54,Photography

In [19]:
print("Final shape:", df.shape)

print("\nMissing values:\n", df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

print("\nData types:\n", df.dtypes)

Final shape: (30087, 15)

Missing values:
 post_id             0
upload_date         0
media_type          0
likes               0
comments            0
shares              0
saves               0
reach               0
impressions         0
caption_length      0
hashtags_count      0
followers_gained    0
traffic_source      0
engagement_rate     0
content_category    0
dtype: int64

Duplicate rows: 1

Data types:
 post_id              object
upload_date          object
media_type           object
likes               float64
comments            float64
shares              float64
saves               float64
reach               float64
impressions         float64
caption_length      float64
hashtags_count      float64
followers_gained    float64
traffic_source       object
engagement_rate     float64
content_category     object
dtype: object

In [20]:
df.to_csv('/content/Instagram_Analytics_Cleaned.csv', index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [21]:
# Remove duplicates
df = df.drop_duplicates()

# Fix traffic_source
df['traffic_source'] = df['traffic_source'].astype(str).str.strip().replace({
    'profile': 'Profile',
    'external': 'External'
})

# Fix content_category
df['content_category'] = df['content_category'].astype(str).str.strip().replace({
    'beauty': 'Beauty',
    'fitness': 'Fitness',
    'travel': 'Travel'
})

# Convert shares to integer
df['shares'] = df['shares'].round().astype(int)

# Convert other count columns to integer
count_cols = [
    'likes', 'comments', 'saves', 'reach', 'impressions',
    'caption_length', 'hashtags_count', 'followers_gained'
]

for col in count_cols:
    df[col] = df[col].round().astype(int)

# Round engagement rate
df['engagement_rate'] = df['engagement_rate'].round(2)

# Final validation
print("Duplicate rows:", df.duplicated().sum())

print("\nTraffic Source values:")
print(sorted(df['traffic_source'].unique()))

print("\nContent Category values:")
print(sorted(df['content_category'].unique()))

print("\nData types:")
print(df.dtypes)

# Save final cleaned dataset
df.to_csv('/content/Instagram_Analytics_Final_Clean.csv', index=False)

print("\nFinal clean dataset saved successfully.")

Duplicate rows: 0

Traffic Source values:
['Explore', 'External', 'Hashtags', 'Home Feed', 'Profile', 'Reels Feed']

Content Category values:
['Beauty', 'Comedy', 'Fashion', 'Fitness', 'Food', 'Lifestyle', 'Music', 'Photography', 'Technology', 'Travel']

Data types:
post_id              object
upload_date          object
media_type           object
likes                 int64
comments              int64
shares                int64
saves                 int64
reach                 int64
impressions           int64
caption_length        int64
hashtags_count        int64
followers_gained      int64
traffic_source       object
engagement_rate     float64
content_category     object
dtype: object

Final clean dataset saved successfully.

In [22]:
print("Duplicate rows:", df.duplicated().sum())

print("\nMissing values:\n", df.isnull().sum())

print("\nTraffic Source values:")
print(sorted(df['traffic_source'].unique()))

print("\nContent Category values:")
print(sorted(df['content_category'].unique()))

print("\nMedia Type values:")
print(sorted(df['media_type'].unique()))

print("\nData types:\n", df.dtypes)

Duplicate rows: 0

Missing values:
 post_id             0
upload_date         0
media_type          0
likes               0
comments            0
shares              0
saves               0
reach               0
impressions         0
caption_length      0
hashtags_count      0
followers_gained    0
traffic_source      0
engagement_rate     0
content_category    0
dtype: int64

Traffic Source values:
['Explore', 'External', 'Hashtags', 'Home Feed', 'Profile', 'Reels Feed']

Content Category values:
['Beauty', 'Comedy', 'Fashion', 'Fitness', 'Food', 'Lifestyle', 'Music', 'Photography', 'Technology', 'Travel']

Media Type values:
['Carousel', 'Photo', 'Reel', 'Video']

Data types:
 post_id              object
upload_date          object
media_type           object
likes                 int64
comments              int64
shares                int64
saves                 int64
reach                 int64
impressions           int64
caption_length        int64
hashtags_count        int64
followers_gained      int64
traffic_source       object
engagement_rate     float64
content_category     object
dtype: object